@baseUrl = http://localhost:3000

### AppControllerGetHello

# @name AppControllerGetHello
GET {{baseUrl}}/

# Notes

### NotesControllerFindAll

# @name NotesControllerFindAll
GET {{baseUrl}}/notes

### NotesControllerFindOne

# @name NotesControllerFindOne
GET {{baseUrl}}/notes/note/1

### NotesControllerFindOneAlt

# @name NotesControllerFindOneAlt
GET {{baseUrl}}/notes/notealt/1

### NotesControllerCreate

# @name NotesControllerCreate
POST {{baseUrl}}/notes
Content-Type: application/json

{
    "id": 1,
    "note": "This is a note"
}

### NotesControllerUpdate

# @name NotesControllerUpdate
PATCH {{baseUrl}}/notes/noteupdate/1
Content-Type: application/json

{
    "note": "This is a note3",
    "update": true
}
