@baseUrl = http://localhost:3000

### AppControllerGetHello
# @name AppControllerGetHello
GET {{baseUrl}}/

# Notes

### List all notes
# @name NotesControllerFindAll
GET {{baseUrl}}/notes

### List all notes with query params
# @name NotesControllerFindAllWithQueryParams
GET {{baseUrl}}/notes/queryparams/?limite=23&offset=7

### List a specific note by ID
# @name NotesControllerFindOne
GET {{baseUrl}}/notes/note/2

### List a specific note by ID
# @name NotesControllerFindOneAlt
GET {{baseUrl}}/notes/notealt/1

### Create a note
# @name NotesControllerCreate
POST {{baseUrl}}/notes
Content-Type: application/json


{
    "text": "This is a new note 3",
    "from": "me",
    "to": "you"
}

### Update a note
# @name NotesControllerUpdate
PATCH {{baseUrl}}/notes/note/3
Content-Type: application/json

{
    "read": true
}

### Remove a specific note by ID
# @name NotesControllerRemove
DELETE {{baseUrl}}/notes/3